/***********************************************************************
 * $Id: DataBaseConstants.java,v1.0 2012-8-7 上午09:56:20 $
 * 
 * @author: RodJohn
 * 
 * (c)Copyright 2011 Topvision All rights reserved.
 ***********************************************************************/
package com.topvision.platform.util;

/**
 * @author RodJohn
 * @created @2012-8-7-上午09:56:20
 * 
 */
public final class DataBaseConstants {
    public static final String ORACLE = "Oracle";
    public static final String MYSQL = "MySQL";
    public static final String TOPOLOGY_TABLE = "ENTITY ENTITYADDRESS TOPOFOLDER ENTITYFOLDERRELA ENTITYSNAP SNMPPARAM ENTITYTYPE";
    public static final String SERVER_TABLE = "ENTITY FOLDERCATEGORY TOPOFOLDER ACTIONTYPE ACTION ALERTTYPE LEVELS ALERT ALERTCOMMENT ALERTFILTER ALERTTYPEACTIONRELA EVENTTYPE EVENT EVENT2ALERT CONNECTIVITY MONITOR MONITORVALUE MONITORVALUEDAILY MONITORVALUEHOURLY ENTITYADDRESS ENTITYATTRIBUTE ENTITYCORP ENTITYFOLDERRELA ENTITYMONITORITEM RESOURCECATEGORY ENTITYTYPE FOLDERUSERGROUPRELA GOOGLEENTITY GRAPH GRAPHEDGE GRAPHVERTEX HISTORYALERT HOSTSERVICE INTERCEPTORLOG LINK LOGICPANEIFINDEX MAPNODE PORT PORTPERF PORTPERFDAILY PORTPERFHOURLY PORTSNAP SERVICES SNMPPARAM THRESHOLD THRESHOLDENTITYRELA THRESHOLDMONITORRELA TOPOLABEL TOPOLOGYPARAM SOFTWAREINSTALLED RUNPROCESS MACPREFIXES VIRTUALNETWORK VIRTUALPRODUCTRELATION PRODUCTSNMPPARAM ENTITYPRODUCTRELATION PERFMONITOR USERATTENTION USERCUSTOMLIZATION";
    public static final String EVENT_TABLE = "";
    public static final String PERFORMANCE_TABLE = "";
    public static final String PLATFORM_TABLE = "VERSIONCONTROL USERS DATADICTIONARY DEPARTMENT FAVOURITEFOLDER NAVIGATIONBUTTON FUNCTIONITEM MENUITEM TOOLBARBUTTON BUTTONMENU GOOGLELOCATION PLACE PORTLETCATEGORY PORTLETITEM PORTLETVIEW PORTLETVIEWRELA REPORT REPORTTEMPLATE REPORTTASK REPOSITORY ROLE ROLENAVIRELA ROLEFUNCTIONRELA ROLEMENURELA ROLEBUTTONRELA STAFF SYSTEMLOG SYSTEMPREFERENCES USERDEPARTMENTRELA USERGROUP USERGROUPRELA USERPLACERELA USERPORTLETRELA USERPREFERENCES USERROLERELA IMAGEDIRECTORY IMAGEFILE ENGINESERVER OPERATORHISTORY";
    // private static String TOPOLOGY_TABLE="";
    // private static String TOPOLOGY_TABLE="";
    public static final String EPON_TABLE = "OLTATTRIBUTE OLTFANRELATION OLTFANATTRIBUTE OLTFANSTATUS OLTPOWERRELATION OLTPOWERATTRIBUTE OLTPOWERSTATUS OLTSLOTRELATION OLTSLOTATTRIBUTE OLTSLOTSTATUS OLTSNIRELATION OLTSNIATTRIBUTE OLTPONRELATION OLTPONATTRIBUTE OLTONURELATION OLTONUATTRIBUTE OLTONUPONRELATION OLTONUPONATTRIBUTE OLTUNIRELATION OLTUNIATTRIBUTE OLTVLANGLOBALINFO OLTTOPALARMCODEMASK OLTTOPALARMINSTANCEMASK OLTTRAPCONFIG OLTPERFTHRESHOLD PERFSTATCYCLE PERFSTATSGLOBALSET OLTSTPGLOBALSETTABLE BATCHCONFIGRECORDS OLTPORTMIRRORCONFIG OLTPORTTRUNKCONFIG OLTVLANCONFIG PERFSTATS15TABLE PERFSTATS24TABLE OLTVIFPRIIPCONFIG OLTVIFSUBIPCONFIG MONITORBASEINFO MONITORPORTRELATION MONITORINDEXRELATION OLTMONITORVALUE EPONCURRENTSTATS EPONSTATSRECORD EPONEVENTTYPERELATION OLTACLLISTTABLE OLTACLRULEENTRY OLTACLPORTACLLISTTABLE OLTQOSDEVICEBASEQOSMAPENTRY OLTQOSDEVICEBASEQOSPOLICYENTRY OLTQOSPORTBASEQOSMAPENTRY OLTQOSPORTBASEQOSPOLICYENTRY OLTIGMPENTITYENTRY OLTIGMPTOPMCOLTCONFMGMTOBJS OLTIGMPTOPMCSNICONFMGMTOBJS OLTIGMPTOPMCONUVLANTRANSENTRY OLTIGMPCTRLMPACKGENTRY OLTIGMPPROXYPARAENTRY OLTIGMPFORWARDINGENTRY OLTIGMPTOPMCONUENTRY OLTIGMPTOPMCUNICONFIGENTRY OLTIGMPCTRLMUSERAUTHENTRY OLTIGMPTOPCONTROLLEDMCCDRENTRY OLTIGMPMCFORWARDINGSLOTTABLE OLTIGMPMCFORWARDINGPORTTABLE OLTIGMPMCFORWARDINGONUTABLE OLTSNIREDIRECT OLTSNISTORMINFO OLTSTPPORTTABLE OLTPORTVLAN OLTSNIMACADDRESSMANAGEMENT OLTPONQINQ OLTPONSTORMINFO OLTPONONUAUTHMODE OLTPONONUAUTOAUTHMODE OLTVLANAGG OLTVLANTRANSLATION OLTVLANTRUNK OLTTOPVLANAGG OLTTOPVLANQINQ OLTTOPVLANTRANS OLTTOPVLANTRUNK OLTONUTYPEINFO OLTAUTHENTICATION ONUBLOCKAUTHEN OLTONUUPGRADE OLTSLATABLE OLTUNIRATELIMIT OLTUNISTORMINFO ONUPORTVLAN ONUVLANAGG ONUVLANTRANSLATION ONUVLANTRUNK ONUAUTOUPGPROFILE ONUAUTOUPGBAND TOPPONPSGRPCONFIG OLTPONOPTICAL OLTSNIOPTICAL ONUPONOPTICAL";
    // public static final String CMC_TABLE =
    public static final String CC_TABLE = "CMCENTITYRELATION CMCATTRIBUTE CMCEMSCONFIG CMCIPMANAGE CMCDHCPGIADDRCONFIG CMCDHCPINTIPTABLE CMCDHCPMODECONFIG CMCDHCPSERVERCONFIG CMCEXTATTRIBUTEB DOLSNMPPARAM MACDOMAINBASEINFO MACDOMAINSTATUSINFO CMCMODULATIONPROFILEINFO CMCPORTRELATION CMCDOWNCHANNELBASEINFO CMCDOWNCHANNELSTATICINFO CMCUPCHANNELBASEINFO CMCUPCHANNELSIGNALQUALITYINFO CMCUPCHANNELSTATICINFO CMCPORTATTRIBUTE CMCPORTPERF CMCCMRELATION CMATTRIBUTE CMATTRIBUTEEXTCPECONTROL CPECMRELATION CPEATTRIBUTE CMCSERVICEFLOWRELATION DYNAMICSERVICEFLOWSTATS SERVICEFLOWATTRIBUTE SERVICEFLOWSTATUS SERVICEFLOWCMRELATION SERVICEFLOWPARAMSETRELATION SERVICEFLOWPARAMSET SERVICEFLOWPKGCLASSRELATION QOSPKTCLASS SERVICECLASS PERFNOISELAST PERFNOISEHIS PERFCHANNELUTILIZATIONLAST PERFCHANNELUTILIZATIONHIS DEVEVCONTROL PERFCHANNELCMNUMLAST PERFCHANNELCMNUMHIS PERFUSBITERRORRATELAST PERFUSBITERRORRATEHIS PERFCHANNELSPEEDSTATICLAST PERFCHANNELSPEEDSTATICHIS PERFSYSTEMHIS CMCEVENTTYPERELATION CMCDHCPBUNDLE CMCDHCPOPTION60 CMCDHCPBASECONFIG CMCVLANPRIIPMANAGE CMCVLANPRIMARYINTERFACE CMC8800BSNICONFIG";
    public static final String AP_TABLE = "AP APALERTSTRATEGY APCONFIG APGROUP APGROUPRELATION APPRECONFIG APREBOOTTASK APREBOOTFAIL APSCONFIG APSTATUS APTRAPSERVER APTSRELATION APUPGRADETASK APUPGRADEFAIL BLACKLIST WHITELIST";
    public static final String ALL_TABLE = PLATFORM_TABLE + " " + SERVER_TABLE + " " + EPON_TABLE + " " + CC_TABLE;
}
