var top_menu = {
	'lang_home'	     : '首页',
	'lang_setup'     : '基本配置',
	'lang_advanced'  : '高级配置',
	'lang_wireless'  : '无线配置',
	'lang_status'    : '状态',
	'lang_management': '管理',
	'lang_welcome'   : '欢迎登录',
	'lang_logout'    : '注销',
    'logout_zte'         : '<img src="/html/skin/logout.gif" />',
	'language'       : '<img src="/html/skin/english.gif" />'
};

var sub_menu = {
	//status
	'Word_status'					: "状态",
	'lang_system_msg'				: '系统信息',
	'lang_lan_clients'				: "主机列表",
	'lang_lan_status'				: "LAN统计信息",
	'lang_connection_status'			: "WAN连接状态",
	'lang_wan_status'				: "WAN统计信息",
	'lang_wireless_connection'			: "WLAN连接状态",
	'lang_wireless_status'				: "WLAN统计信息",
	'lang_usb_status'				: "USB信息"  ,
	//setup
	'Word_setup'					: '基本配置',
	'lang_submenu_lan'					: ' 端口配置',
	'lang_lan'						: '端口绑定',
	'lang_lan_advanced'					: 'LAN高级配置',
	'lang_submenu_wan'					: ' WAN配置',
	'lang_connected'					: 'WAN',
	'lang_wan_advanced'					: 'WAN高级配置',
	'lan_wan_vlan'						: 'WAN VLAN' ,	
	//advanced
	'Word_advanced'				: "高级配置",
	'lang_alg'				: "ALG",
	'lang_dhcp_filter'    : "DHCP过滤",
	'lang_mac_list'				: "MAC过滤",
	'lang_napt'				: "虚拟服务器",
	'lang_dnsAgent'			: "DNS代理",
	'lang_dnsConfig'		: "DNS配置",
	'lang_qosInterface'		: "QoS接口配置",
	'lang_qosQueue'			: "QoS队列配置",
	'lang_qosFlux'			: "QoS流量分类配置",
	'lang_dos'			: "防攻击",
	'lang_ipList'			: "IP过滤",
	'lang_local_access_ctrl'	: "本地访问控制",
	'lang_remote_access_ctrl'	: "远程访问控制",
	'lang_remote_ctrl'		: "远程访问控制",
	'lang_igmpAgent'		: "IGMP代理",
	'lang_igmpSnooping'		: "IGMP Snooping",
	'lang_mldctl'			: "MLD代理",
	'lang_mldsnooping'		: "MLD Snooping",
	'lang_staticRouting'		: "静态路由",
	'lang_dynamicRouting'		: "动态路由",
	'lang_sntp'			: "时间",
	'lang_nat_priority'		: "NAT优先级",
	'lang_dmz'			: "DMZ",
	'lang_upnp'			: "UPnP配置",
	'lang_urlFilter'        	: "URL过滤",
	'lang_stp'			: "STP",
	'lang_wan_monitor'      	: "WAN监控配置" ,
	//wireless
	'Word_wireless'			: '无线配置',
	'lang_wireless_setup'   	: '无线基本配置',
	'lang_wireless_vap'	   	 : 'VAP配置',
	'lang_wireless_advanced'	: '无线高级配置',
	'lang_wireless_scanap'  	: '无线AP扫描',
	'lang_wps_setup'		: 'WPS配置'  ,
	//management
	'Word_management'				: '管理',
	'lang_system_management'			: '系统管理',
	'lang_user_management'				: '用户管理',
	'lang_ping'					: 'Ping诊断',
	'lang_tr069'					: 'TR069配置',
	'lang_snmp'					: 'SNMP配置',
	'lang_CAPWAP'                       		: 'CAPWAP配置',
	'lang_config_update'				: '配置文件升级',
	'lang_img_update'				: 'IMG文件升级',
	'lang_log'					: '日志配置',
	'lang_logview'					: '日志查看',
	'lang_help'						:' 帮助'
};
 