var data_language = {
	title : 'VAP配置',
	innerHTML : {
		lang_enableVap: '启用VAP',
		lang_hideSsid : '隐藏SSID',
		lang_isolateSsid : 'SSID内部隔离',
		lang_UcIsolate : '二层隔离(单播)',
		lang_McIsolate : '二层隔离(组播)',
		lang_bcisolate :　'二层隔离(广播)',
		lang_maxVapNum : 'VAP终端最大接入数',
		lang_workMode : '工作模式',
		lang_ParentApMac : '上级AP MAC地址',
		lang_root_jumps : '与Root相距的跳数',
		lang_wdsEnable : '开启WDS功能',
		lang_wlanSecurity : '无线安全',
		lang_encrypt : '加密',
		lang_auth : '认证方式',
		lang_wepEnable : '启用WEP功能',
		lang_wepStrong : '加密强度',
		lang_chooseWepKey : '选择WEP Key',
		lang_wapEnable : '启用WPA功能',
		lang_passwordType : '密码类型',
		lang_phrase : '预共享密钥',
		lang_keyRefresh : '密钥更新',
		lang_keyLiftTime : '组密钥生存期',
		lang_LifeTime_Info : '(60~65535秒)',
		lang_fstRadius : '首选Radius',
		lang_serverIP1 : '服务器IP地址',
		lang_serverPort1 : '端口',
		lang_shareSecret1 : '共享密钥',
		lang_secRadius : '备用Radius',
		lang_serverIP2 : '服务器IP地址',
		lang_serverPort2 : '端口',
		lang_shareSecret2 : '共享密钥',
		lang_radiusBilling : 'Radius计费',
		lang_fstRadiusCount : '首选Radius计费端口',
		lang_secRadiusCount : '备用Radius计费端口',
		lang_Encrypt_on : '启用',
		lang_Encrypt_off : '禁用',
		lang_when_stop_update_key : '当任何成员终止连接时更新组密钥',
		lang_update_report_interval : '更新报告间隔',
		lang_second : '(秒)',
		lang_JoinBridge : '加入到LANGroup中',
		lang_ManagementVapIP : 'IP地址',
		lang_ManagementVapMask : '子网掩码',
		lang_FlowThresEnable : '按流量限制新用户接入',
		lang_FlowThres : '流量大小',
		lang_wapiPskSetting : 'WAPI-PSK设置',
		lang_WAPi_Phrase : '预共享密钥',
		lang_wapiCertSetting : 'WAPI-Cert设置',
		lang_CertServerIP : '证书服务器IP',
		lang_CertServerPort : '证书服务器端口',
		lang_CertManagement : '证书管理'
	},
	value : {
		submit : '提交',
		refresh : '刷新',
		INPUT_UpdateAuth : '上传证书'
	},
	dynamic : {
		wireless_disabled : '无线已被禁用',
		wireless_modifing : '正在处理配置,请等待...'
	}
}
